#!/usr/bin/env bash
# install nginx and configure it to listen on port 80
# it must return a page that contains the string Hello World!

sudo apt-get update
sudo apt-get install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx start
