#!/usr/bin/env bash
# The bash script that displays the content of the file /etc/passwd

FILENAME="/etc/passwd"

while read -r read_file
do
	echo "${read_file}"
done < ${FILENAME} | cut -d ":" -f 1,3,6
