#!/usr/bin/env bash
# A bash script that runs Nginx as the nginx user

# Configure nginx to listen on ports 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# sets permissions so that, (U)ser 
chmod 644 /etc/nginx/nginx.conf

# stop the apache service
pkill apache2

#start the nginx service as user: nginx
sudo -u nginx service nginx start
